### ISSUE TITLE
tutorial detail 페이지 user organization 표시 문제

### ISSUE THREAD

**Issue by myungseokang** [pythonkr/pyconkr-2017#106]
<img width="934" alt="2017-08-01 5 55 01" src="https://user-images.githubusercontent.com/12431127/28817310-c75120f2-76e2-11e7-9cf8-4333e744c83c.png">

https://github.com/pythonkr/pyconkr-2017/blob/develop/pyconkr/templates/pyconkr/tutorialproposal_detail.html#L29

Organization 부분이 `None` 그대로 표시되는 것 같아 이슈 남깁니다.

**Comment by SehoNoh** [comment]
제보 감사합니다. 확인해보겠습니다 :)

**Comment by SehoNoh** [comment]
수정돼서 적용되었습니다. 감사합니다 :)
