### ISSUE TITLE
스폰서 slug에 특수문자 들어가면 스폰서 전체가 안 나오던 버그

### ISSUE THREAD

**Issue by SehoNoh** [pythonkr/pyconkr-2017#108]
제곧내입니다.

@makeajourney 님께서 아산나눔재단의 slug를 **asan** -> **asan-nanum** 으로 수정하시려고 하셔서
https://www.pycon.kr/2017/about/sponsor/asan URL을 https://www.pycon.kr/2017/about/sponsor/asan-nanum 으로 변경되려고 했는데
기존의 정규표현식은 특수문자를 제외한 알파벳+숫자만 적용되는 `\w` 로 돼있어서, 공백을 제외한 문자인 `\S` 로 변경

이라고 적긴 했는데, PR에 적을 걸 그랬네요 넘 길어짐

**Comment by SehoNoh** [comment]
내년에 좀더 자세한 수정을 위해 이슈는 close 하지 않고 냄겨둡니다.

**Comment by makeajourney** [comment]
slogan(x) -> slug(o) 
원래 slug에는 `-`가 포함되는 것이 보통이기 때문에, 기존 regex에서 `-`만 추가하는 형태로 수정하는 것이 올바르게 보입니다. \S는 모든 특수문자를 포함하기 때문에 올바르지 않아 보입니다.

**Comment by makeajourney** [comment]
스폰서 url 관련 이슈이므로 해당 이슈만 fix하고 close하시죠.

**Comment by SehoNoh** [comment]
수정 배포되었습니다.
