### ISSUE TITLE
얼리버드 결제 테스트

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#12]
* uwsgi의 gevent 작동 여부 확인
* 다수의 동접자 상황을 시뮬레이션 하는 로드테스트
* 다수의 동접자 기준을 작년의 얼리버드 오픈 시간당시 접수된 건수를 세서 추정해봐야 할듯 함.

궁극적으로는 짧은 시간에 많은 결제자가 몰렸을때 문제없이 결제가 이루어지면 됩니다.

**Comment by tebica** [comment]
@woojing 결제 준비를 위해 필요한 내용을 추가 부탁드립니다.

**Comment by woojing** [comment]
여유있게는 동접 200정도 생각해야할듯 합니다.

**Comment by tebica** [comment]
성공적이었기에 닫습니다
