### ISSUE TITLE
참석 확인증 인쇄기능 추가

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#125]
참석 확인증 요청이 꽤 많이 들어왔고, 들어올 예정입니다.
* 파이콘이 끝나고나서 확인증을 출력할 수 있는 기능 (우리 "등록영수증" 메뉴와 비슷한 형식)
* 발권이 실제로 된 사람에 한해서 참석 확인증 출력 가능

기타
* 현장에서 튜토리얼, 스프린트도 참석확인증 가능한지에 대한 문의가 있었으나, 이건 좀 힘들겠죠?
* "등록영수증"은 카드결제 정보 기준이라고 알고있음. 이번에 표 발급시 이름은 "프로필에 이름이 있으면 프로필 기준, 없으면 카드 결제 정보 기준"이었는데 참석 확인증도 그렇게 하는게 어떨까요?
참석 확인증 이름을 바꿔달라고 하면 현재 "등록영수증"과 같은 기준으로 이름을 보여주면 참석자가 이름수정이 불가능함.

**Comment by kucuny** [comment]
@tebica 튜토리얼, 스프린트 참석확인증은 우리 시스템에서 추후 일반 등록과 동일한 프로세스가 만들어지면 가능할 것 같습니다.

**Comment by tebica** [comment]
@NohSeho 세호님, 오늘 작업한거 PR 어딨어요?

**Comment by tebica** [comment]
이 작업은 완료되었으므로 닫습니다.
