### ISSUE TITLE
teaser 페이지에 og tag 추가하기

### ISSUE THREAD

**Issue by SehoNoh** [pythonkr/pyconkr-2017#15]
* http://ogp.me/ 참고해서 teaser 페이지에 og tag 추가하기
  * og 태그 내용은 작년 파이콘 페이지를 참고해주세요
* 발표자 일정도 공지
* 컨퍼런스 / 튜토리얼 기간을 나눠서 명시
  * 8월 12~13 : 컨퍼런스
  * 8월 14~15 : 튜토리얼과 스프린트

**Comment by tebica** [comment]
Closing this issue.
