### ISSUE TITLE
Responsive web in teaser page

### ISSUE THREAD

**Issue by mu-hun** [pythonkr/pyconkr-2017#25]
# 스크린샷
<img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/18275254_1166356376827266_7733101247261042774_n.jpg?oh=725469ac55a8d0ee5f8a17200a05e4d3&oe=59B98581" width="400px">

> OS : Android 6.0
> 웹 브라우저 : 크롬

# 티져 페이지 모바일 대응 요청합니다.

1. 스크린의 크기에 따라 폰트의 크기가 변하지만 아직 많이 부족합니다.
2. 우측에 여백이 있습니다.

**Comment by tebica** [comment]
의견 감사합니다.
티저 페이지의 생명이 얼마 남지 않았고 공식 페이지 준비에 집중하려고 합니다
모바일 대응은 현재로서는 힘이 듭니다.

**Comment by mu-hun** [comment]
답변 감사합니다.
