### ISSUE TITLE
결제 수단에서 가상 계좌 처리

### ISSUE THREAD

**Issue by SehoNoh** [pythonkr/pyconkr-2017#43]
결제 수단에서 가상 계좌에 대한 처리가 안 돼있음

**Comment by tebica** [comment]
@NohSeho 가상계좌가 왜 실패했는지 저번에 적으셨던걸로 기억하는데 다시 한번 알려주시겠어요?

**Comment by tebica** [comment]
정보를 입력하고 버튼을 누르면 응답이 없음

**Comment by SehoNoh** [comment]
'가상계좌에 대한 기능 구현(분기 처리)이 안 돼있다' 정도면 될 것 같습니다.

**Comment by SehoNoh** [comment]
Closed with #57
