### ISSUE TITLE
일부 엘리먼트 뒤로 이벤트가 전달되지 않아 특정 상황에서 메뉴 이용이 불가능합니다

### ISSUE THREAD

**Issue by devunt** [pythonkr/pyconkr-2017#44]
![image](https://cloud.githubusercontent.com/assets/337728/26090141/eb411814-3a3d-11e7-88a0-390efc82fd81.png)
뒷 배경 >가 다른 엘리먼트 위로 올라올 경우 메뉴를 포함한 모든 링크가 클릭 불가능합니다.

일단 `pointer-events: none;`[1] 을 추가하면 대체로 잘 되니 참고 부탁드립니다.

대상 엘리먼트:
- `.bracket_line`
- `.bracket_fill`

[1] http://caniuse.com/#feat=pointer-events

**Comment by SehoNoh** [comment]
제보 감사합니다. :)

**Comment by SehoNoh** [comment]
resolved by https://github.com/pythonkr/pyconkr-2017/pull/48
