### ISSUE TITLE
후원 안내 메뉴 클릭시 메뉴 2개가 선택됩니다

### ISSUE THREAD

**Issue by devunt** [pythonkr/pyconkr-2017#46]
스크린샷과 같이 `파이콘 한국` - `후원 안내` 메뉴 클릭시 우상단의 메뉴 목록에서 `후원사 목록` (`sponser`)과 `후원 안내` (`sponsership`) 메뉴 둘 다 active 상태로 표시됩니다. 반대의 경우에는 성립하지 않습니다.

![image](https://cloud.githubusercontent.com/assets/337728/26090532/8ee78f78-3a40-11e7-9ac9-473bf63e481a.png)

**Comment by devunt** [comment]
상단 드롭다운 메뉴도 동일합니다.

![image](https://cloud.githubusercontent.com/assets/337728/26090607/14d75faa-3a41-11e7-91f6-bf17c693fe5e.png)

**Comment by SehoNoh** [comment]
제보 감사합니다 :)

**Comment by tebica** [comment]
resolved by #49
