### ISSUE TITLE
구매 상품명 변경

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#47]
아래 구매 상품명을 Pycon-earlybird 로 변경
![image](https://cloud.githubusercontent.com/assets/1404067/26098006/5d80a55c-3a61-11e7-822d-951d343d4ffd.png)

**Comment by SehoNoh** [comment]
Patron도 같이 
PyCon-Earlybird 
PyCon-Patron으로 수정했습니다. 

다만 이미 결제된 항목들은 따로 수정이 불가능한 듯한데, 
iamport cs에 메일 남겨볼까요?

**Comment by tebica** [comment]
@NohSeho 기존 것까지 수정할 필요는 없을거 같아요.
수고하셨어요 닫습니다.

**Comment by SehoNoh** [comment]
개인 후원자 쪽 코드에 반영 안 된 부분이 있어서 reopen 합니다.

**Comment by SehoNoh** [comment]
https://github.com/pythonkr/pyconkr-2017/pull/55
수정됐습니다.
