### ISSUE TITLE
2017년도 DB 백업 추가

### ISSUE THREAD

**Issue by channprj** [pythonkr/pyconkr-2017#50]
## 현재
웹서버에서 dumpdata 로 DB가 백업되고 있지만 2017년도 데이터는 백업이 되고 있지 않음.

## 개선안
2017년도 데이터도 백업되도록 코드 추가.

**Comment by tebica** [comment]
@channprj 이 수정 완료.
내일 잘 되고있는지 확인후 close

**Comment by channprj** [comment]
`solr-thumbnail` 관련 `dumpdata` 가 동작하지 않는 이슈가 있었으나 `migrate` 가 되어 있지 않아서 발생한 문제.
동작 확인 완료 후 이슈 종료.
