### ISSUE TITLE
티셔츠 사이즈 받는 기능 넣기

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#54]

**Comment by iiogmgo** [comment]
- [x]  티셔츠 사이즈 컬럼 추가
- [x]  등록 페이지에 사이즈 입력하도록 기능 추가
- [ ]  등록상태(status) 페이지에서 사이즈 수정/입력 하도록 기능 추가

**Comment by iiogmgo** [comment]
https://github.com/pythonkr/pyconkr-2017/tree/top_size

**Comment by iiogmgo** [comment]
`등록상태(status) 페이지에서 사이즈 수정/입력 하도록 기능 추가` 에 대한 작업을 이어가주실 분 8ㅅ8

**Comment by iiogmgo** [comment]
일단 닫습니다
