### ISSUE TITLE
튜토리얼 제출 후 프로필-등록에서 표기 오류

### ISSUE THREAD

**Issue by Bill-Park** [pythonkr/pyconkr-2017#76]
튜토리얼을 신청하였으나 **Sprint에 제출해주셔서 감사합니다**로 나오고 있습니다.
Tutorial의 **발표안 제출하기**를 클릭하면 제출한 정보가 나오고 Sprint의 **내 발표안 확인하기**를 누르면 발표안을 작성하는 페이지가 나옵니다.

현재 보이는 프로필 창의 화면입니다.

![profile](https://goo.gl/zHnVRi)

**Comment by SehoNoh** [comment]
https://github.com/pythonkr/pyconkr-2017/commit/a38cc61b7f62cdecf4db532cc6f4705263fc57fe 커밋에서 수정되었습니다. 감사합니다 :)
