### ISSUE TITLE
등록, 명찰 인쇄 관련

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#78]
* 몇번 프린트 되었는지도 확인
* 등록 프린트를 한 개발, 라인프린터로 테스트.
* 장고 어드민에서 프린트 기능.

- [ ] 출력전에 미리보기 페이지 필요, 미리보기 페이지에서 발권횟수 확인도 가능해야함
- [x] 리스트의 전화번호컬럼을 이메일 컬럼으로 교체
- [x] 등록 번호컬럼은 제거
- [x] DB백업 상태 확인

**Comment by Bloodevil** [comment]
#59 와 중복된 이슈입니다. 이슈 합칩니다.

**Comment by SehoNoh** [comment]
전부 작업된 것으로 보입니다. close 해도 될까요?

**Comment by SehoNoh** [comment]
마지막 PR까지 머지 완료됐습니다.
