### ISSUE TITLE
test case test_view_registration_payment 실패중

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#8]
![image](https://cloud.githubusercontent.com/assets/1404067/25565570/0e346f24-2e04-11e7-8dfd-cf7720484e8d.png)

> test_view_registration_payment (pyconkr.tests.PaymentTestCase) ... FAIL
수정 필요 이거 혹시 #6 이 해결하는 이슈 인가요? @kucuny

**Comment by kucuny** [comment]
@tebica 테스트 케이스를 보고 수정한건 아니고 @woojing 님이 python3로 컨버팅하고 있다는 이야기를 듣고 저도 코드를 보던 중 수정한 것입니다.

**Comment by woojing** [comment]
https://travis-ci.org/pythonkr/pyconkr-2017/builds/231137697
