### ISSUE TITLE
모바일 시간표가 깨짐

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2017#80]

**Comment by SehoNoh** [comment]
PR https://github.com/pythonkr/pyconkr-2017/pull/96 으로 수정됐습니다.

<img width="743" alt="screen shot 2017-07-26 at 6 22 15 pm" src="https://user-images.githubusercontent.com/1144643/28614251-13eba85e-7230-11e7-85c3-306b79634214.png">
